version: '2.0'
services:
  frontend:
    image: myfront
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IP=localhost
    ports:
      - 8081:3000
  backend:
    image: myback
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      