version: '2.0'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IP=${IP}
    ports:
      - 8081:3000
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      